# When the alarm is armed in away mode, send notification
alias: 'Alarm is armed in away mode'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: "armed_away"
action:
  - service: notify.mobile_app_oneplus_a6003
    data:
      title: "Alarm system"
      message: "ALARM! The alarm is armed in away mode {{ states('sensor.date_time') }}"
