# When the alarm is armed in home mode, send notification
alias: 'Alarm is armed in home mode'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: "armed_home"
action:
  - service: notify.mobile_app_oneplus_a6003
    data:
      title: "Alarm system"
      # Using multi-line notation allows for easier quoting
      message: >
        ALARM! The alarm is armed in home mode {{ states('sensor.date_time') }}
