# When arming the alarm, play a sound from the gateway
alias: 'Play audio cue when arming the alarm'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: "arming"
action:
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: !secret xiaomi_gw_mac
      ringtone_id: 8
      ringtone_vol: 10