# Send a notification with a camera image attachment when the alarm is triggered
alias: 'Send notification when alarm triggered'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: "triggered"
action:
  - service: downloader.download_file
    data_template:
      url: "http://192.168.1.186:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=foscam&pwd=48241200ab"
      filename: "snap.jpg"
      overwrite: true
  - service: notify.mobile_app_oneplus_a6003
    data:
      title: "Alarm system"
      message: "ALARM! The alarm has been triggered"
      data:
        image: "/local/snap.jpg"