alias: 'Send notification when alarm is in pending status'
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_system
    to: "pending"
action:
  - service: notify.mobile_app_oneplus_a6003
    data:
      title: "Alarm system"
      message: "ALARM! The alarm is in pending status at {{ states('sensor.date_time') }}"