- alias: Test1
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001b179d9
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.gateway_light_286c07f1c2cd
    data:
      brightness: 255
      color_name: red
  - service: xiaomi_aqara.play_ringtone
    data:
      ringtone_id: 8
      ringtone_vol: 10
  - service: automation.turn_on
    data:
      entity_id: automation.MOTION_OFF

- alias: Notify on startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: notify.scott
    data_template:
      message: "System is up and running"

- alias: Notify on shutdown
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - service: notify.scott
    data_template:
      message: "System is shutting down"

- alias: Alert when motion detected while away
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001b179d9
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sensor.heating_tado_mode
    state: HOME
  action:
  - service: notify.scott
    data_template:
      message: "MOTION DETECTED!!"
