# Security alarm automations
#Using sensors to trigger the alarm
- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: group.motion_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: group.door_window_sensor
      to: "open"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm_system
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.alarm_system

#Send a notification when the alarm is triggered
- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_system
      to: "triggered"
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm system"
        message: "ALARM! The alarm has been triggered"

#Send a Notification when the Alarm is Armed (Away/Home), Disarmed and in Pending Status
- alias: 'Send notification when alarm is Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_system
      to: "disarmed"
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm system"
        message: "ALARM! The alarm is Disarmed at {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is in pending status'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_system
      to: "pending"
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm system"
        message: "ALARM! The alarm is in pending status at {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is Armed in Away mode'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_system
      to: "armed_away"
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm system"
        message: "ALARM! The alarm is armed in Away mode {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is Armed in Home mode'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_system
      to: "armed_home"
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm system"
        # Using multi-line notation allows for easier quoting
        message: >
          ALARM! The alarm is armed in Home mode {{ states('sensor.date_time') }}

# 1. When alarm is armed and motion is detected, start alarm on the gateway
- alias: Siren when motion detected
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001b179d9
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.arm_alarm
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_286c07f1c2cd
      data:
        brightness: 255
        color_name: red
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomi_gw_mac
        ringtone_id: 1
        ringtone_vol: 10
    - service: automation.turn_on
      data:
        entity_id: automation.MOTION_OFF

# 1b. When arming the alarm, play a sound from the gateway and send a notification
- alias: Alarm arming visual/textual notification
  trigger:
    platform: state
    entity_id: input_boolean.arm_alarm
    from: 'off'
    to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomi_gw_mac
        ringtone_id: 8
        ringtone_vol: 10
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm"
        message: "Alarm armed"

# 1c. When disarming the alarm, play a sound from the gateway and send a notification
- alias: Alarm disarming visual/textual notification
  trigger:
    platform: state
    entity_id: input_boolean.arm_alarm
    from: 'on'
    to: 'off'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xiaomi_gw_mac
        ringtone_id: 4
        ringtone_vol: 10
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm"
        message: "Alarm disarmed"

# 2. When oneplus is away and motion is detected, fire an alarm
- alias: Alert when any motion detected while away
  trigger:
    platform: state
    entity_id: group.motion_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: sensor.heating_tado_mode_2
    state: 'AWAY'
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Alarm"
        message: ":police_car: Warning! Motion detected! :police_car:"

# Home assistant startup and shutdown notifications
- alias: Notify on startup
  trigger:
    - event: start
      platform: homeassistant
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Notification"
        message: ":star: Home Assistant is starting! :star:"

- alias: Notify on shutdown
  trigger:
    - event: shutdown
      platform: homeassistant
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Notification"
        message: "Home Assistant is shutting down! :pensive: :pensive:"

# When noone is at home, turn off all lights and switches
- alias: Turn off lights and switches when noone is at home
  trigger:
    platform: state
    entity_id: sensor.heating_tado_mode_2
    from: 'HOME'
    to: 'AWAY'
  action:
  - service: script.turn_on
    data:
      entity_id: script.lights_out

- alias: Turn off lights when watching Netflix
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.tv_source
    to: 'Netflix'
  action:
    - service: light.turn_off

- alias: Turn on study lights when motion detected in study
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000313db82
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.study_lamp

- alias: Turn off study lights when no motion detected in study for 30 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000313db82
    to: 'off'
    for:
      minutes: 30
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - light.study_lamp

- alias: Turn on lamps if presence changed to home and sun is down
  trigger:
    platform: state
    entity_id: sensor.heating_tado_mode_2
    from: 'AWAY'
    to: 'HOME'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
  - service: script.turn_on
    data:
      entity_id: script.essential_lights_on

# Toggle living room and dinner lights with main switch single click
- alias: Toggle living room and kitchen lights
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001aaad1c
      click_type: single
  action:
  - service: script.turn_on
    data:
      entity_id: script.essential_lights_toggle

# Turn all lights off on main switch double click
- alias: Turn all lights off on main switch double click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001aaad1c
      click_type: double
  action:
  - service: script.turn_on
    data:
      entity_id: script.lights_out

# Turn all lights off on bedroom switch left single click
- alias: Turn all lights off
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0002c5a7c2
      click_type: single
  action:
  - service: script.turn_on
    data:
      entity_id: script.lights_out

# Toggle study lights on study switch left single click
- alias: Toggle study lights
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0002cb155a
      click_type: single
  action:
  - service: script.turn_on
    data:
      entity_id: script.study_lights_toggle

# Turn night light on for 10 minutes
- alias: Turn night light on for 10 minutes
  initial_state: 'off'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0002c5a7c2
      click_type: single
  action:
    - service: light.turn_on
      entity_id: light.living_room_lamp
      data:
        brightness: 100
        color_name: red
    - service: timer.start
      data:
        entity_id: timer.night

# Turn night light off after 10 minutes
- alias: Turn night light off after 10 minutes
  initial_state: 'off'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.night
  action:
    service: homeassistant.turn_off
    data:
      entity_id:
        - light.living_room_lamp

# Warning if water is detected
- alias: Warning if water is detected
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d0002773fa1
    from: 'off'
    to: 'on'
  action:
    - service: notify.mobile_app_oneplus_a6003
      data:
        title: "Warning"
        message: "Water leakage detected! :potable_water:"

- id: lounge_snapshot
  alias: Lounge snapshot
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001b179d9
    to: 'on'
  action:
  - service: downloader.download_file
    data_template:
      url: "http://192.168.1.186:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=foscam&pwd=48241200ab"
      filename: "snap.jpg"
      overwrite: true
  - service: notify.mobile_app_oneplus_a6003
    data:
      title: "Home Alert"
      message: "Motion Detected"
      data:
        image: "/local/snap.jpg"
