homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Athens
  customize: !include customize.yaml
  # whitelist_external_dirs: !secret whitelist_dirs

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  use_include_order: True
  include:
    domains:
      - binary_sensor
      - sensor
      - switch
      - media_player
      - device_tracker
      - light
      - climate
      - input_boolean

history_graph:
  graph1:
    name: Heating Graph
    entities:
      - sensor.heating_temperature
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daytime_high_temperature
      - sensor.dark_sky_overnight_low_temperature
    hours_to_show: 24
    refresh: 60

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

media_player:
  - platform: denonavr
    host: 192.168.1.201
    name: Denon
    # show_all_sources: True / False
    # timeout: POSITIVE INTEGER
    # zones:
    #   - zone: Zone2 / Zone3
    #     name: NAME
  - platform: webostv
    host: 192.168.1.200
    name: TV
    #filename: webostv.conf
    #timeout: 5
    #turn_on_action:
    #  service: persistent_notification.create
    #  data:
    #    message: "Turn on action"
    #customize:
    #  sources:
    #    - livetv
    #    - youtube
    #    - makotv
    #    - netflix

notify:
  - name: discord
    platform: discord
    token: !secret discord_token
  - name: charis
    platform: group
    services:
      - service: discord
        data:
          target: !secret discord_channel_id

weather:
  - platform: darksky
    api_key: !secret darksky_key

input_boolean:
  arm_alarm:
    name: Arm alarm
    initial: off
    icon: mdi:security

# binary_sensor:
#   - platform: bayesian
#     name: In Bed
#     # base probability of sleeping: 8/24 = 33%
#     prior: 0.33
#     # Once the sensor hits a probability threshold of 95%, fire the rule
#     probability_threshold: 0.95
#     observations:
#       - entity_id: group.all_lights
#         prob_given_true: 0.7
#         platform: state
#         to_state: 'off'
#       # - entity_id: remote.watch_roku
#       #   prob_given_true: 0.75
#       #   platform: state
#       #   to_state: off
#       - entity_id: sun.sun
#         prob_given_true: 0.7
#         platform: state
#         to_state: below_horizon

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
  - mac: !secret xiaomi_gw_mac
    key: !secret xiaomi_gw_key

light:
- platform: yeelight
  devices:
    192.168.1.110:
      name: Diner lamp
    192.168.1.111:
      name: Living room lamp
    192.168.1.112:
      name: Kitchen lamp
    192.168.1.113:
      name: Study lamp

device_tracker:
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

tado:
  username: !secret tado_username
  password: !secret tado_password

automation: !include automations.yaml
#automation: !include_dir_merge_list automations
group: !include groups.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
