- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - cloud_cover
    - summary
    - icon
    - temperature
    - apparent_temperature
    - precip_probability
    - humidity
    - daily_summary
    - hourly_summary
    - temperature_low
    - temperature_high
    - wind_bearing
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
  scan_interval:
    minutes: 5
# Used for the ui statistics
- platform: history_stats
  name: Home this week
  entity_id: sensor.heating_tado_mode_2
  state: 'HOME'
  type: ratio
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Away this week
  entity_id: sensor.heating_tado_mode_2
  state: 'AWAY'
  type: ratio
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Heating ON this week
  entity_id: sensor.heating_power_2
  state: 'ON'
  type: ratio
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Heating OFF this week
  entity_id: sensor.heating_power_2
  state: 'OFF'
  type: ratio
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
- platform: history_stats
  name: TV on this week
  entity_id: media_player.tv
  state: 'On'
  type: ratio
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
# Used for the alarm system notifications
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
