title: My Home!
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: entities
        title: Home status
        entities:
          - group.status
      - type: history-graph
        title: Heating
        entities:
          - history_graph.heating_graph
      - type: history-graph
        title: Heating alternative
        entities:
          - sensor.heating_temperature
          - sensor.dark_sky_temperature
          - sensor.dark_sky_daytime_high_temperature
          - sensor.dark_sky_overnight_low_temperature
      - type: weather-forecast
        entity: weather.dark_sky
      - type: glance
        title: Lights
        entities:
          - group.all_lights
      - type: map
        aspect_ratio: 100%
        default_zoom: 8
        entities:
          - device_tracker.oneplus
          - zone.home
      - type: entities
        title: Switches
        entities:
          - group.all_switches
      - type: entities
        title: Configuration
        entities:
          - group.configuration
      - type: entities
        title: Automation
        entities:
          - group.all_automations
      - type: entities
        title: Media player
        entities:
          - group.mediaplayer
      - type: entities
        title: Heating panel
        entities:
          - climate.heating
      - type: thermostat
        entity: climate.heating
      - type: entities
        title: Security camera
        entities:
          - camera.foscam_camera
      - type: entity-filter
        id: peoplehome
        entities:
          - device_tracker.oneplus
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
      - type: entity-filter
        id: applianceson
        entities:
          - light.kitchen_lamp
          - light.diner_lamp
          - light.living_room_lamp
          - light.study_lamp
          - media_player.tv
          - media_player.denon
          - sensor.heating_power
          - switch.plug_158d0001dcab9e
        state_filter:
          - 'on'
          - 'ON'
        card:
          type: glance
          title: Activated appliances
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## Living room
        - type: horizontal-stack
          cards:
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: light.living_room_lamp
                  icon: mdi:desk-lamp
                  tap_action: toggle
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: media_player.tv
                  icon: mdi:television
                  tap_action: toggle
        - type: horizontal-stack
          cards:
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: media_player.denon
                  icon: mdi:headphones
                  tap_action: toggle
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: switch.plug_158d0001dcab9e
                  icon: mdi:power-socket-eu
                  tap_action: toggle
