title: My Home!
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: entities
        title: Home status
        entities:
          - sensor.home_this_week
          - sensor.away_this_week
          - sensor.heating_on_this_week
          - sensor.heating_off_this_week
          - sensor.tv_on_this_week
      - type: entities
        entities:
          - entity: binary_sensor.motion_sensor_158d0001b179d9
            secondary_info: last-changed
          - entity: binary_sensor.motion_sensor_158d000313db82
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0001a9805b
            secondary_info: last-changed
      - type: button
        name: Lights out
        icon: mdi:power
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.lights_out
      - type: glance
        title: Lights and switches
        show_state: false
        entities:
          - entity: light.kitchen_lamp
            name: Kitchen lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.living_room_lamp
            name: Living room lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.study_lamp
            name: Study lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.diner_lamp1
            name: Diner lamp 1
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.diner_lamp2
            name: Diner lamp 2
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.diner_lamp3
            name: Diner lamp 3
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.tv_lamp1
            name: TV lamp 1
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.tv_lamp2
            name: TV lamp 2
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.floor_lamp
            name: Floor lamp
            icon: mdi:floor-lamp-torchiere-variant
            tap_action:
              action: toggle
          - entity: switch.plug_158d0001dcab9e
            name: Living room switch
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
      # - type: entities
      #   title: Configuration
      #   entities:
      #     - input_boolean.arm_alarm
      - type: entities
        title: Media player
        entities:
          - media_player.tv
          - media_player.denon
          - media_player.denon_avr_x2400h
      - type: media-control
        entity: media_player.denon_avr_x2400h
      - type: entities
        title: Security camera
        entities:
          - camera.foscam_camera
      - type: picture-glance
        title: Home camera
        entities:
          - binary_sensor.switch_158d0001aaad1c
        camera_image: camera.foscam_camera
      - type: entity-filter
        id: applianceson
        entities:
          - light.kitchen_lamp
          - light.living_room_lamp
          - light.study_lamp
          - light.diner_lamp1
          - light.diner_lamp2
          - light.diner_lamp3
          - light.tv_lamp1
          - light.tv_lamp2
          - light.floor_lamp
          - media_player.tv
          - media_player.denon_avr_x2400h
          - sensor.heating_power_2
          - switch.plug_158d0001dcab9e
        state_filter:
          - 'on'
          - 'ON'
          - 'Playing'
          - 'idle'
        card:
          type: glance
          title: Activated appliances
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        image: false
        name: Roborock
        buttons: true
  - icon: mdi:weather-partly-cloudy
    title: Weather
    cards:
      - type: grid
        square: false
        cards:
        - type: sensor
          name: Living room temperature
          entity: sensor.heating_temperature_2
          graph: line
          detail: 2
          hours_to_show: 6
        - type: sensor
          name: Bedroom temperature
          entity: sensor.temperature_158d0002c91220
          graph: line
          detail: 2
          hours_to_show: 6
        - type: sensor
          name: Living room humidity
          entity: sensor.heating_humidity_2
          graph: line
          detail: 2
          hours_to_show: 6
        - type: sensor
          name: Bedroom humidity
          entity: sensor.humidity_158d0002c91220
          graph: line
          detail: 2
          hours_to_show: 6
        - type: sensor
          name: Environmental temperature
          entity: sensor.dark_sky_temperature
          graph: line
          detail: 2
          hours_to_show: 6
        - type: sensor
          name: Precipitation probability
          entity: sensor.dark_sky_precip_probability
          graph: line
          detail: 2
          hours_to_show: 6
      - type: weather-forecast
        entity: weather.dark_sky
      - type: thermostat
        entity: climate.heating
  - title: Rooms
    icon: mdi:floor-plan
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## Living room
        - type: horizontal-stack
          cards:
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: light.living_room_lamp
                  icon: mdi:floor-lamp
                  tap_action: toggle
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: media_player.tv
                  icon: mdi:television
                  tap_action: toggle
        - type: horizontal-stack
          cards:
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: media_player.denon
                  icon: mdi:headphones
                  tap_action: toggle
            - type: glance
              show_name: false
              show_state: false
              columns: 1
              entities:
                - entity: switch.plug_158d0001dcab9e
                  icon: mdi:power-socket-eu
                  tap_action: toggle
  - title: Presence
    icon: mdi:crosshairs-gps
    cards:
      - type: entity-filter
        id: peoplehome
        entities:
          - device_tracker.oneplus
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
      - type: map
        aspect_ratio: 100%
        default_zoom: 8
        entities:
          - device_tracker.oneplus
          - zone.home
