resources:
  - url: /local/mini-graph-card-bundle.js?v=0.10.0
    type: module
  - url: /local/xiaomi-vacuum-card.js?v=4.4.0
    type: module

title: My Home!
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Home status
        entities:
          - sensor.home_this_week
          - sensor.away_this_week
          - sensor.heating_on_this_week
          - sensor.heating_off_this_week
          - sensor.tv_on_this_week
      - type: entities
        entities:
          - group.motion_sensors
          - group.door_window_sensors
      - type: button
        name: Lights out
        icon: mdi:power
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.lights_out
      - type: glance
        title: Lights and switches
        show_state: false
        entities:
          - entity: light.kitchen_lamp
            name: Kitchen lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.living_room_lamp
            name: Living room lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.study_lamp
            name: Study lamp
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
          - entity: light.diner_lamp1
            name: Diner lamp 1
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.diner_lamp2
            name: Diner lamp 2
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.diner_lamp3
            name: Diner lamp 3
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.tv_lamp1
            name: TV lamp 1
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.tv_lamp2
            name: TV lamp 2
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: light.floor_lamp
            name: Floor lamp
            icon: mdi:floor-lamp-torchiere-variant
            tap_action:
              action: toggle
          - entity: switch.plug_158d0001dcab9e
            name: Living room switch
            # icon: mdi:lightbulb-outline
            tap_action:
              action: toggle
      - type: entities
        title: Media player
        entities:
          - group.media_player
      - type: media-control
        entity: media_player.denon_avr_x2400h_2
      - type: media-control
        entity: media_player.spotify_charis
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.robot_vacuum
      - type: entity-filter
        id: applianceson
        entities:
          - light.kitchen_lamp
          - light.living_room_lamp
          - light.study_lamp
          - light.diner_lamp1
          - light.diner_lamp2
          - light.diner_lamp3
          - light.tv_lamp1
          - light.tv_lamp2
          - light.floor_lamp
          - switch.plug_158d0001dcab9e
          - media_player.tv
          - media_player.denon_avr_x2400h_2
          - media_player.spotify_charis
          - sensor.heating_power_2
        state_filter:
          - 'on'
          - 'ON'
          - 'Playing'
          - 'idle'
        card:
          type: glance
          title: Activated appliances
      - type: alarm-panel
        name: Alarm panel
        entity: alarm_control_panel.alarm_system
      - type: entities
        title: Security camera
        entities:
          - camera.foscam_camera
      - type: picture-glance
        title: Home camera
        entities:
          - binary_sensor.switch_158d0001aaad1c
        camera_image: camera.foscam_camera
  - icon: mdi:weather-partly-cloudy
    title: Weather
    cards:
      - type: horizontal-stack
        title: "Living room"
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            icon: mdi:home-thermometer
            hours_to_show: 6
            points_per_hour: 10
            entities:
              - entity: sensor.heating_temperature_2
          - type: custom:mini-graph-card
            name: Humidity
            icon: mdi:water-percent
            hours_to_show: 6
            points_per_hour: 10
            line_color: blue
            entities:
              - entity: sensor.heating_humidity_2
      - type: horizontal-stack
        title: "BME280"
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            icon: mdi:home-thermometer
            hours_to_show: 6
            points_per_hour: 10
            entities:
              - entity: sensor.bme280_temperature
          - type: custom:mini-graph-card
            name: Humidity
            icon: mdi:water-percent
            hours_to_show: 6
            points_per_hour: 10
            line_color: blue
            entities:
              - entity: sensor.bme280_humidity
          - type: custom:mini-graph-card
            name: Pressure
            icon: mdi:gauge
            hours_to_show: 6
            points_per_hour: 10
            line_color: green
            entities:
              - entity: sensor.bme280_pressure
      - type: horizontal-stack
        title: "Environment"
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            icon: mdi:home-thermometer
            hours_to_show: 6
            points_per_hour: 10
            entities:
              - entity: sensor.dark_sky_temperature
          - type: custom:mini-graph-card
            name: Precipitation probability
            icon: mdi:weather-pouring
            hours_to_show: 6
            points_per_hour: 10
            line_color: blue
            entities:
              - entity: sensor.dark_sky_precip_probability
      - type: thermostat
        entity: climate.heating
      - type: vertical-stack
        title: "Sensing"
        cards:
        - type: horizontal-stack
          title: "Lux"
          cards:
            - type: custom:mini-graph-card
              name: BH1750 Lux
              icon: mdi:weather-sunny
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.bh1750_lux
            - type: custom:mini-graph-card
              name: TSL2591 Lux
              icon: mdi:weather-sunny
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.tsl2591_lux
        - type: horizontal-stack
          title: "Light"
          cards:
            - type: custom:mini-graph-card
              name: TSL2591 Full spectrum light
              icon: mdi:lightbulb-variant-outline
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.tsl2591_full_spectrum_light
            - type: custom:mini-graph-card
              name: TSL2591 Infrared light
              icon: mdi:lightbulb-variant-outline
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.tsl2591_infrared_light
            - type: custom:mini-graph-card
              name: TSL2591 Visible light
              icon: mdi:lightbulb-variant-outline
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.tsl2591_visible_light
        - type: horizontal-stack
          title: "Air quality"
          cards:
            - type: custom:mini-graph-card
              name: CCS811 Total VOC
              icon: mdi:molecule-co2
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.ccs811_total_volatile_organic_compound
            - type: custom:mini-graph-card
              name: CCS811 CO2
              icon: mdi:molecule-co2
              hours_to_show: 6
              points_per_hour: 10
              entities:
                - entity: sensor.ccs811_eco2_value
  - title: Presence
    icon: mdi:crosshairs-gps
    cards:
      - type: entity-filter
        id: peoplehome
        entities:
          - device_tracker.oneplus
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
      - type: map
        aspect_ratio: 100%
        default_zoom: 8
        entities:
          - device_tracker.oneplus
          - zone.home
