title: My Awesome Home!
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
     #- type: markdown
     #   title: Greetings
     #   content: >
     #     Welcome **master**!
      - type: entities
        title: Home status
        entities:
          - group.status
          - history_graph.heating_graph
      - type: entities
        title: Lights
        entities:
          - group.all_lights
      - type: entities
        title: Switches
        entities:
          - group.all_switches
        # The markdown card will render markdown text.
      - type: entities
        title: Configuration
        entities:
          - group.configuration
      - type: entities
        title: Automation
        entities:
          - group.all_automations
      - type: entities
        title: Media player
        entities:
          - group.mediaplayer
      - type: entities
        title: Heating panel
        entities:
          - climate.heating
      - id: peoplehome
        type: entity-filter
        entities:
          - device_tracker.oneplus
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
      - id: applianceson
        type: entity-filter
        entities:
          - light.kitchen_lamp
          - light.diner_lamp
          - light.living_room_lamp
          - light.study_lamp
          - media_player.tv
          - media_player.denon
          - sensor.heating_power
        state_filter:
          - 'on'
          - 'ON'
        card:
          type: glance
          title: Activated appliances
    # View tab title.
  - icon: mdi:monitor
    title: Monitor
    # Unique id for direct access /lovelace/${id}. If you don't specify one, it is added automatically.
    id: monitor
    # Optional background (overwrites the global background).
    #background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
      - id: peoplehome
        type: entity-filter
        entities:
          - device_tracker.oneplus
        state_filter:
          - 'home'
        card:
          type: glance
          title: People at home
      - id: applianceson
        type: entity-filter
        entities:
          - light.kitchen_lamp
          - light.diner_lamp
          - light.living_room_lamp
          - light.study_lamp
          - media_player.tv
          - media_player.denon
          - sensor.heating_power
        state_filter:
          - 'on'
          - 'ON'
        card:
          type: glance
          title: Activated appliances

       # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.kitchen_lamp
