alias: On main switch double click turn all lights off and arm the alarm
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001aaad1c
      click_type: double
action:
  - service: script.turn_on
    data:
      entity_id: script.lights_out
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarm_system
