alias: Toggle study lights
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.wall_switch_left_158d0002cb155a
    click_type: single
action:
- service: script.turn_on
  data:
    entity_id: script.study_lights_toggle