alias: Turn all lights off on main switch double click or bedroom switch single click
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001aaad1c
      click_type: double
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0002c5a7c2
      click_type: single
action:
- service: script.turn_on
  data:
    entity_id: script.lights_out