alias: Turn off lights and switches when noone is at home
trigger:
  platform: state
  entity_id: sensor.heating_tado_mode_2
  from: 'HOME'
  to: 'AWAY'
action:
- service: script.turn_on
  data:
    entity_id: script.lights_out